# Generated by Django 2.2.6 on 2019-10-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=5)),
                ('jugadores', models.IntegerField()),
                ('encargado', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('liga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga.Liga')),
            ],
        ),
    ]
