# Generated by Django 2.2.6 on 2019-10-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_liga', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('categoria', models.IntegerField()),
                ('jugadores', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
            ],
        ),
    ]
